"""Adiciona tabela Receita e relacionamentos

Revision ID: 13b367dd3406
Revises: f8b8e6aa2ef0
Create Date: 2025-10-22 21:51:54.053769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13b367dd3406'
down_revision = 'f8b8e6aa2ef0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receitas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('consulta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['consulta_id'], ['consultas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('receitas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_receitas_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receitas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_receitas_timestamp'))

    op.drop_table('receitas')
    # ### end Alembic commands ###
